name: Deploy

on:
  pull_request:
    branches: 
      - main
    types: [closed]

jobs: 
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: 12
      - run: npm ci
      - run: npm run build-storybook
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: storybook-static # The folder the action should deploy.