name: Publish

on:
  pull_request:
    branches: 
      - main
    types: [closed]

jobs: 
  test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: 16
      - run: npm ci
      - run: npm run test
  
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: [test]
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: 16
      - run: npm ci
      - run: npm run semantic-release
        env: 
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}